export default {
  // -----// LOGIN //-----//
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  // ----- // SIGNUP // ----- //
  SIGNUP_START: 'SIGNUP_START',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',
  // -----// LOGOUT //-----//
  LOGOUT_START: 'LOGOUT_START',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
  // -----// LOGOUT //-----//
  GET_CURRENT_USER_START: 'GET_CURRENT_USER_START',
  GET_CURRENT_USER_SUCCESS: 'GET_CURRENT_USER_SUCCESS',
  GET_CURRENT_USER_FAILURE: 'GET_CURRENT_USER_FAILURE',
  // -----// TRANSACTIONS //-----//
  GET_ALL_TRANSACTIONS_FROM_BACK: 'GET_ALL_TRANSACTIONS_FROM_BACK',
  DELETE_TRANSACTION: 'DELETE_TRANSACTION',
  EDIT_TRANSACTION: 'EDIT_TRANSACTION',
  LOADER_ON:'TRANSACTION_LOADER_ON',
  LOADER_OFF:'TRANSACTION_LOADER_OFF',
  SET_ERROR:'TRANSACTION_SET__ERROR',
  RESET_ERROR:'TRANSACTION_SET__ERROR',
  FILTER_ALL: 'TRANSACTION_FILTER_ALL',
  FILTER_INCOMES: 'TRANSACTION_FILTER_INCOMES',
  FILTER_EXPENCES: 'TRANSACTION_FILTER_EXPENCES',
  FILTER_TRANSACTIONS_BY_INCOMES : 'FILTER_TRANSACTIONS_BY_INCOMES',
  FILTER_TRANSACTIONS_BY_EXPENCES : 'FILTER_TRANSACTIONS_BY_EXPENCES'

};
